feature/implement-excel-import-service
holydrug/digital-commerce-service pull request #40
Opened 2022-09-17 09:50 UTC by vovamargaryan23

2022-09-17 10:44 UTC, holydrug requested changes
Логику пока вообще не трогал, пробежался быстро по тому, что первое в галаза кидается

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/pom.xml
> +    <groupId>org.example</groupId>
посмотреть как в ветке develop сделаны модули разные и их pom изменить

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/pom.xml
> +        <maven.compiler.source>18</maven.compiler.source>
тут тоже измени и посмотри как в других модулях всё устроено

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
> +    @Autowired
Не использовать аноташку autowired, посмотри как в других модулях нужные бины дотягиваются

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/controller/ExcelImportController.java
> +    private ExcelImportService excelImportService;
то же самое, избавится от autowired

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/controller/ExcelImportController.java
> +    @GetMapping("/")
Начнем с того, зачем указывать явно корень для get mapping, если ничего дополнительного нет
Зачем тебе вообще стучатся к этому эндпоинту, убери

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/entity/Price.java
> +public class Price {
У тебя все энтити давнейшей версии, обнови до текущего состояния гитом всё или вручную

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/entity/partner/Partner.java
> +public class Partner {
Устаревшая версия тоже энтити

2022-09-17 10:44 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/PartnerImportService.java
> +    @Autowired
избавится от Autowired тоже

2022-09-17 13:15 UTC, holydrug requested changes
Чекни мои коменты

2022-09-17 13:15 UTC, holydrug commented on commerce-excel-service/pom.xml
> +
nice

2022-09-17 13:15 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/DistributionImportService.java
> +public class DistributionImportService {
Что это? Убери, если не нужно

2022-09-17 13:15 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/PartnerImportService.java
> +        this.partnerRepository.save(new Partner(name, PartnerType.valueOf(type)));
Тебе не нужно указывать this перед использованием бина, убери

2022-09-17 13:15 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
>  import java.io.FileInputStream;
Ты в этом сервисе не избавился от аутовайред анотахи, почему?
Убирай ее

2022-09-17 13:30 UTC, holydrug requested changes
Чекни коменты

2022-09-17 13:30 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
>      @Autowired
Почему снова тут эта бедная твоя любимая autowired осталось-то :)?

2022-09-17 13:30 UTC, holydrug commented on commerce-excel-service/src/main/java/service/controller/ExcelImportController.java
> +                excelImportService.setFile(file);
nice

2022-09-17 13:30 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
> +        fileName = file.getOriginalFilename();
nice

2022-09-17 13:30 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/PartnerImportService.java
> +        partnerRepository.save(new Partner(name, PartnerType.valueOf(type)));
nice

2022-09-17 13:58 UTC, vovamargaryan23 commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
>      @Autowired
какого.. , я же 100% удалял...

2022-09-18 10:27 UTC, holydrug requested changes

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
> +    private final PartnerImportService partnerImportService;
nice

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/pom.xml
> +    <artifactId>commerce-excel-service</artifactId>
Нужно поменять название сервиса на что-то вроде commerce-import-excel-service

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/pom.xml
> +            <version>8.0.30</version>
Посмотри как сделано в других моделях, вынеси версии в проперти

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/pom.xml
> +            <version>5.2.2</version>
соответственно все проперти

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/src/main/java/service/controller/ExcelImportController.java
> +        if (file != null) {
If выглядит некрасиво, заверни всё в Optional -> если не знаешь что это такое, самое время прочитать, добавили в java 8, чтобы боротся как раз с NPE , так какой-то метод должен Function ФИ принимать, через него можно завернуть

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/src/main/java/service/controller/ExcelImportController.java
> +            try {
Тебе нужно убрать try catch блок отсюда и прокидывать ошибку на уровень выше, чтобы ничего такого не было
Создай exception Holder, который будет ловить (ДЛЯ ВСЕГО МОДУЛЯ), допустим, твой RuntimeException (любой unchecked получается)
И обрабатывать какой-то реализацией, типо уже ExcelNotFoundException который будет реализовать глобальный exception твой и говорить, что файла нет

Если что, я щас за компом, могу объяснить религию такого подхода

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/ExcelImportService.java
> +                switch (cell.getCellType()) {
Я пока не придумал как, но нужно будет обязательно убрать switch case конструкцию, мб вынести в отдельный метод проверку, суть в том, что никто никогда его не использует и это прям некрасиво

2022-09-18 10:27 UTC, holydrug commented on commerce-excel-service/src/main/java/service/service/PartnerImportService.java
> +        String nameAndType = partnerName.split("\\.")[0];
Когда ты так делаешь (указываешь какой-то expresiion в коде -> это называется магичиские строки в коде) так некрасиво делать, выноси своей regex в филды и делай их константами (psf)

2022-10-08 13:13 UTC, closed without merging