Feature/implement exceptions
holydrug/digital-commerce-service pull request #53
Opened 2022-09-23 19:03 UTC by vovamargaryan23

2022-09-23 20:10 UTC, holydrug requested changes

2022-09-23 20:10 UTC, holydrug commented on commerce-entity-initialization/src/main/java/com/digital/commerce/service/entity/apiError/ApiError.java
> +package com.digital.commerce.service.entity.apiError;
плохое название пакета, никто никогда не пишет их с большой буквы, почитай про Naming Convention, измени название учитывая это

2022-09-23 20:10 UTC, holydrug commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityAlreadyExistsException.java
> +package com.commerce.nomenclature.update.exception;
пакет в корне модуля делается для разделения по слоям -> слой переименуй на error

2022-09-23 20:10 UTC, holydrug commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/service/NomenclatureUpdateServiceImpl.java
> +            if(nomenclatureRepository.existsById(nomenclature.getId())){
Тут я неправильно поставил задачу, моя ошибка, не entityAlredy экзист тут нужно, а заверни одну строчку в опшнл и кидай ошибку, что энттити коруптед и пиши бэд реквест что-нибудь такое

2022-09-23 20:12 UTC, holydrug commented
1) также измени комиты, наполни их информацией, по фразе updated ApiError ничего не понятно, измени все коменты так
2) название ветки ничего не говорит, сделай нормальное, посмотри как до этого делали мы
3) пул реквест должен соотвествовать ветке, измени и это

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-entity-initialization/src/main/java/com/digital/commerce/service/entity/apiError/ApiError.java
> +    private List errors;
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityAlreadyExistsException.java
> +public class EntityAlreadyExistsException extends ModuleException {
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityAlreadyExistsException.java
> +        super(s);
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityExceptionHandler.java
> +public class EntityExceptionHandler {
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityExceptionHandler.java
> +    @ExceptionHandler(value = {EntityAlreadyExistsException.class})
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-entity-initialization/src/main/java/com/digital/commerce/service/entity/apiError/ApiError.java
> +package com.digital.commerce.service.entity.apiError;
исправил

2022-09-24 07:19 UTC, vovamargaryan23 commented on commerce-nomenclature-update-service/src/main/java/com/commerce/nomenclature/update/exception/EntityAlreadyExistsException.java
> +package com.commerce.nomenclature.update.exception;
исправил

2022-09-24 07:44 UTC, closed without merging